version: '2.0'
services:

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - outside
    hostname: rabbit
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=512Mib
    ports:
      - 5672:5672

  memcached:
    image: memcached:latest
    networks:
      - outside
    hostname: memcached
    ports:
      - 11211:11211

  mongodb:
    image: mongo:latest
    networks:
      - outside
    hostname: mongo
    ports:
      - 27017:27017

#  node1:
#    image: app
#    networks:
#      - outside
#    hostname: node1
#    ports:
#      - 8080:8080

#  node2:
#    image: app
#    networks:
#      - outside
#    hostname: node2
#    ports:
#      - 8080:8080

# node3:
#    image: app
#    networks:
#      - outside
#    hostname: node3
#    ports:
#      - 8080:8080
